version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - mongo-data:/data/db
        # environment:
        #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        restart: always

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - '6379:6379'
        restart: always

volumes:
    mongo-data:
        driver: local
